version: '3'

services:
  
  nginx:
    image: nginx:1.17.6-alpine
    container_name: nginx    
    ports: 
      - "3050:80"

  node1:  
    image: nginx:1.17.6-alpine 
    volumes: 
      - /home/douglas/Documentos/exer-docker/server1:/usr/share/nginx/html
    container_name: node1   
    ports: 
      - "8080"            

  node2:  
    image: nginx:1.17.6-alpine 
    volumes: 
      - /home/douglas/Documentos/exer-docker/server2:/usr/share/nginx/html
    container_name: node2 
    ports: 
      - "8080"  